import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import { cn } from '@/lib/utils';
import FlashCardsProvider from '@/providers/FlashCardsProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn('bg-neutral-950 text-neutral-300', inter.className)}>
        <FlashCardsProvider>
          <main className='h-screen overflow-hidden'>{children}</main>
          <Navbar />
        </FlashCardsProvider>
      </body>
    </html>
  );
}
